version: '3.1'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    network_mode: "host"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    ports:
      - 3000:3000
    network_mode: "host"

  # jaeger:
  #   image: jaegertracing/all-in-one:1.49.0
  #   container_name: jaeger
  #   environment:
  #     - COLLECTOR_OTLP_ENABLED=true
  #   ports:
  #     - 16686:16686
  #     - 4317:4317
  #     - 4318:4318

  clickhouse:
    image: clickhouse/clickhouse-server:23.3
    container_name: clickhouse
    environment:
      - CLICKHOUSE_DB=llm
      - CLICKHOUSE_USER=greptime
      - CLICKHOUSE_PASSWORD=greptime
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - 9000:9000 # Native Protocol port (also referred to as ClickHouse TCP protocol).
      - 8123:8123 # HTTP API Port for http requests.
    network_mode: "host"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8123"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    # volumes:
    #   - ./clickhouse/data:/var/lib/clickhouse
    #   - ./clickhouse/logs:/var/log/clickhouse-server

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.86.0
    volumes:
      - ./otel-collector-config.yml:/etc/otelcol-contrib/config.yaml
    # depends_on:
    #   clickhouse:
    #     condition: service_healthy
    ports:
      - 1888:1888 # pprof extension
      # - 8888:8888 # Prometheus metrics exposed by the collector
      # - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 55679:55679 # zpages extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
    network_mode: "host"
