receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 5s
    send_batch_size: 100000

exporters:
  otlp/jaeger:
    endpoint: localhost:14317
    tls:
      insecure: true
  clickhouse:
    endpoint: tcp://localhost:9000?dial_timeout=10s&compress=lz4
    username: greptime
    password: greptime
    database: llm
    logs_table_name: llm_logs
    traces_table_name: llm_traces
    metrics_table_name: llm_metrics
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse, otlp/jaeger]
