{
 "title": "OpenAI in LangChain",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total Cost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model) (langchain_completion_tokens_cost{llm=\"openai\"} + langchain_prompt_tokens_cost{llm=\"openai\"})",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Prompt Cost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model) (langchain_prompt_tokens_cost{llm=\"openai\"})",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Completion Cost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model) (langchain_completion_tokens_cost{llm=\"openai\"})",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Prompt Token Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model) (langchain_prompt_tokens_total{llm=\"openai\"})",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Completion Token Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model) (langchain_completion_tokens_total{llm=\"openai\"})",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "P95 Latency of openai requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.95,\n    sum by(le, model) (rate(langchain_llm_request_duration_milliseconds_bucket{llm=\"openai\"}[$__rate_interval]))\n)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "QPS of openai requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (model) (rate(langchain_llm_request_duration_milliseconds_count{llm=\"openai\"}[$__rate_interval]))",
     "legendFormat": "{{model}}"
    }
   ]
  }
 ]
}