name: shared-steps

runs:
  using: "composite"
  steps:
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
      shell: bash

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
      shell: bash

    - name: Install Dev dependencies
      run: |
        pip install langchain openai pytest ruff mypy pymysql
      shell: bash

    # TODO(yuanbohan): code coverage with pytest-cov
    - name: Test with pytest
      run: |
        pytest tests/ -v
      shell: bash

    - name: Lint & Format with Ruff
      run: |
        ruff check --output-format=github .
        ruff format .
      shell: bash

    - name: Static Type Checking with mypy
      run: |
        mypy $(git ls-files '*.py') --check-untyped-defs
      shell: bash