name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'examples/**'
      - '.gitignore'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'examples/**'
      - '.gitignore'

env:
  GREPTIMEAI_HOST: ${{ secrets.GREPTIMEAI_HOST }}
  GREPTIMEAI_USERNAME: ${{ secrets.GREPTIMEAI_USERNAME }}
  GREPTIMEAI_PASSWORD: ${{ secrets.GREPTIMEAI_PASSWORD }}
  GREPTIMEAI_DATABASE: ${{ secrets.GREPTIMEAI_DATABASE }}
  GREPTIMEAI_TOKEN: ${{ secrets.GREPTIMEAI_TOKEN }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  ci-3-8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Run shared steps
        uses: ./.github/actions/

  ci-3-9:
    runs-on: ubuntu-latest
    needs: ci-3-8

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Run shared steps
        uses: ./.github/actions/

  ci-3-10:
    runs-on: ubuntu-latest
    needs: ci-3-9

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Run shared steps
        uses: ./.github/actions/

  ci-3-11:
    runs-on: ubuntu-latest
    needs: ci-3-10

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Run shared steps
        uses: ./.github/actions/

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
