name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'examples/**'
      - '.gitignore'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'examples/**'
      - '.gitignore'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      # TODO(yuanbohan): code coverage with pytest-cov
      - name: Test with pytest
        run: |
          pip install pytest langchain tiktoken openai
          pytest tests/ -v

      - name: Lint & Format with Ruff
        run: |
          pip install ruff
          ruff check --output-format=github .
          ruff format .
