name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'examples/**'
      - '.gitignore'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'examples/**'
      - '.gitignore'

jobs:
  ci-3-8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: shared-steps
        uses: ./.github/workflows/shared-steps.yml

  ci-3-9:
    runs-on: ubuntu-latest
    needs: ci-3-8

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: shared-steps
        uses: ./.github/workflows/shared-steps.yml

  ci-3-10:
    runs-on: ubuntu-latest
    needs: ci-3-9

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: shared-steps
        uses: ./.github/workflows/shared-steps.yml

  ci-3-11:
    runs-on: ubuntu-latest
    needs: ci-3-10

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: shared-steps
        uses: ./.github/workflows/shared-steps.yml

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
