name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'examples/**'
      - '.gitignore'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'examples/**'
      - '.gitignore'

jobs:
  ci-3-8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Install Dev dependencies
        run: |
          pip install langchain openai pytest ruff mypy pymysql

      # TODO(yuanbohan): code coverage with pytest-cov
      - name: Test with pytest
        env:
          GREPTIMEAI_HOST: ${{ secrets.GREPTIMEAI_HOST }}
          GREPTIMEAI_USERNAME: ${{ secrets.GREPTIMEAI_USERNAME }}
          GREPTIMEAI_PASSWORD: ${{ secrets.GREPTIMEAI_PASSWORD }}
          GREPTIMEAI_DATABASE: ${{ secrets.GREPTIMEAI_DATABASE }}
          GREPTIMEAI_TOKEN: ${{ secrets.GREPTIMEAI_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pytest tests/ -v

      - name: Lint & Format with Ruff
        run: |
          ruff check --output-format=github .
          ruff format .

      - name: Static Type Checking with mypy
        run: |
          mypy $(git ls-files '*.py') --check-untyped-defs

  ci-3-9:
    runs-on: ubuntu-latest
    needs: ci-3-8

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Install Dev dependencies
        run: |
          pip install langchain openai pytest ruff mypy pymysql

      # TODO(yuanbohan): code coverage with pytest-cov
      - name: Test with pytest
        env:
          GREPTIMEAI_HOST: ${{ secrets.GREPTIMEAI_HOST }}
          GREPTIMEAI_USERNAME: ${{ secrets.GREPTIMEAI_USERNAME }}
          GREPTIMEAI_PASSWORD: ${{ secrets.GREPTIMEAI_PASSWORD }}
          GREPTIMEAI_DATABASE: ${{ secrets.GREPTIMEAI_DATABASE }}
          GREPTIMEAI_TOKEN: ${{ secrets.GREPTIMEAI_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pytest tests/ -v

      - name: Lint & Format with Ruff
        run: |
          ruff check --output-format=github .
          ruff format .

      - name: Static Type Checking with mypy
        run: |
          mypy $(git ls-files '*.py') --check-untyped-defs

  ci-3-10:
    runs-on: ubuntu-latest
    needs: ci-3-9

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Install Dev dependencies
        run: |
          pip install langchain openai pytest ruff mypy pymysql

      # TODO(yuanbohan): code coverage with pytest-cov
      - name: Test with pytest
        env:
          GREPTIMEAI_HOST: ${{ secrets.GREPTIMEAI_HOST }}
          GREPTIMEAI_USERNAME: ${{ secrets.GREPTIMEAI_USERNAME }}
          GREPTIMEAI_PASSWORD: ${{ secrets.GREPTIMEAI_PASSWORD }}
          GREPTIMEAI_DATABASE: ${{ secrets.GREPTIMEAI_DATABASE }}
          GREPTIMEAI_TOKEN: ${{ secrets.GREPTIMEAI_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pytest tests/ -v

      - name: Lint & Format with Ruff
        run: |
          ruff check --output-format=github .
          ruff format .

      - name: Static Type Checking with mypy
        run: |
          mypy $(git ls-files '*.py') --check-untyped-defs

  ci-3-11:
    runs-on: ubuntu-latest
    needs: ci-3-10

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Install Dev dependencies
        run: |
          pip install langchain openai pytest ruff mypy pymysql

      # TODO(yuanbohan): code coverage with pytest-cov
      - name: Test with pytest
        env:
          GREPTIMEAI_HOST: ${{ secrets.GREPTIMEAI_HOST }}
          GREPTIMEAI_USERNAME: ${{ secrets.GREPTIMEAI_USERNAME }}
          GREPTIMEAI_PASSWORD: ${{ secrets.GREPTIMEAI_PASSWORD }}
          GREPTIMEAI_DATABASE: ${{ secrets.GREPTIMEAI_DATABASE }}
          GREPTIMEAI_TOKEN: ${{ secrets.GREPTIMEAI_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pytest tests/ -v

      - name: Lint & Format with Ruff
        run: |
          ruff check --output-format=github .
          ruff format .

      - name: Static Type Checking with mypy
        run: |
          mypy $(git ls-files '*.py') --check-untyped-defs

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
