name: "PR Title Checker"

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, edited]

jobs:
  check:
    name: check-pr-title
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: thehanimo/pr-title-checker@v1.3.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: ".github/pr-title-check-config.json"
