{
 "title": "LangChain Observability",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Preview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Cost",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model) (llm_completion_tokens_cost + llm_prompt_tokens_cost)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "QPS of requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (type) (rate(llm_request_duration_ms_count[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Error Distribution by type",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (llm_errors_total)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Cost", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Prompt Cost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model) (llm_prompt_tokens_cost)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Completion Cost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model) (llm_completion_tokens_cost)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  { "title": "Token", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Prompt Token Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model) (llm_prompt_tokens_total)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Completion Token Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model) (llm_completion_tokens_total)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.95,\n    sum by(le, type) (rate(llm_request_duration_ms_bucket[$__rate_interval]))\n)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "QPS of errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(llm_errors_total[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}